version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-task-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - USER1_ID=${USER1_ID}
      - USER1_NAME=${USER1_NAME}
      - USER2_ID=${USER2_ID}
      - USER2_NAME=${USER2_NAME}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - telegram-bot-network
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/data/tasks.db').execute('SELECT 1')"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  telegram-bot-network:
    driver: bridge

volumes:
  bot-data:
    driver: local